.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.2 */

nonmatching D_8009AF08

dlabel D_8009AF08
    /* 8B708 8009AF08 3C000000 */ .word 0x0000003C
enddlabel D_8009AF08

nonmatching D_8009AF0C

dlabel D_8009AF0C
    /* 8B70C 8009AF0C 00000000 */ .word 0x00000000
enddlabel D_8009AF0C

nonmatching D_8009AF10

dlabel D_8009AF10
    /* 8B710 8009AF10 00002000 */ .word 0x00200000
enddlabel D_8009AF10

nonmatching D_8009AF14

dlabel D_8009AF14
    /* 8B714 8009AF14 00200000 */ .word 0x00002000
enddlabel D_8009AF14

nonmatching D_8009AF18

dlabel D_8009AF18
    /* 8B718 8009AF18 609E0E80 */ .word D_800E9E60
    /* 8B71C 8009AF1C 00000000 */ .word 0x00000000
enddlabel D_8009AF18

nonmatching D_8009AF20

dlabel D_8009AF20
    /* 8B720 8009AF20 */ .short 0x0400
    /* 8B722 8009AF22 */ .short 0x0C00
enddlabel D_8009AF20

nonmatching D_8009AF24

dlabel D_8009AF24
    /* 8B724 8009AF24 */ .byte 0x05
    /* 8B725 8009AF25 */ .byte 0x0A
    /* 8B726 8009AF26 */ .byte 0x0F
    /* 8B727 8009AF27 */ .byte 0x14
    /* 8B728 8009AF28 */ .byte 0x1E
enddlabel D_8009AF24

nonmatching D_8009AF29

dlabel D_8009AF29
    /* 8B729 8009AF29 */ .byte 0xFF
enddlabel D_8009AF29

nonmatching D_8009AF2A

dlabel D_8009AF2A
    /* 8B72A 8009AF2A */ .byte 0x00
    /* 8B72B 8009AF2B */ .byte 0x00
enddlabel D_8009AF2A

nonmatching D_8009AF2C

dlabel D_8009AF2C
    /* 8B72C 8009AF2C */ .byte 0x00
enddlabel D_8009AF2C

nonmatching D_8009AF2D

dlabel D_8009AF2D
    /* 8B72D 8009AF2D */ .byte 0x00
enddlabel D_8009AF2D

nonmatching D_8009AF2E

dlabel D_8009AF2E
    /* 8B72E 8009AF2E */ .byte 0x00
    /* 8B72F 8009AF2F */ .byte 0x00
enddlabel D_8009AF2E

nonmatching D_8009AF30

dlabel D_8009AF30
    /* 8B730 8009AF30 */ .byte 0x02
    /* 8B731 8009AF31 */ .byte 0x05
    /* 8B732 8009AF32 */ .byte 0x0A
    /* 8B733 8009AF33 */ .byte 0x14
    /* 8B734 8009AF34 */ .byte 0x32
    /* 8B735 8009AF35 */ .byte 0x00
    /* 8B736 8009AF36 */ .byte 0x00
    /* 8B737 8009AF37 */ .byte 0x00
enddlabel D_8009AF30

nonmatching D_8009AF38

dlabel D_8009AF38
    /* 8B738 8009AF38 */ .byte 0x05
    /* 8B739 8009AF39 */ .byte 0x0A
    /* 8B73A 8009AF3A */ .byte 0x14
    /* 8B73B 8009AF3B */ .byte 0x32
    /* 8B73C 8009AF3C */ .byte 0x64
    /* 8B73D 8009AF3D */ .byte 0x00
    /* 8B73E 8009AF3E */ .byte 0x00
    /* 8B73F 8009AF3F */ .byte 0x00
enddlabel D_8009AF38

.align 2
nonmatching D_8009AF40

dlabel D_8009AF40
    /* 8B740 8009AF40 */ .asciz "%d\n"
    /* 25640A00 */
.align 2
enddlabel D_8009AF40

nonmatching D_8009AF44

dlabel D_8009AF44
    /* 8B744 8009AF44 */ .short 0x0500
enddlabel D_8009AF44

nonmatching D_8009AF46

dlabel D_8009AF46
    /* 8B746 8009AF46 */ .short 0x0001
    /* 8B748 8009AF48 00000100 */ .word 0x00010000
enddlabel D_8009AF46

nonmatching D_8009AF4C

dlabel D_8009AF4C
    /* 8B74C 8009AF4C 0F00F000 */ .word 0x00F0000F
    /* 8B750 8009AF50 000F00F0 */ .word 0xF0000F00
enddlabel D_8009AF4C

.align 2
nonmatching D_8009AF54

dlabel D_8009AF54
    /* 8B754 8009AF54 */ .asciz "\n"
    /* 0A000000 */
.align 2
enddlabel D_8009AF54

.align 2
nonmatching D_8009AF58

dlabel D_8009AF58
    /* 8B758 8009AF58 */ .asciz "%s\n"
    /* 25730A00 */
.align 2
enddlabel D_8009AF58

nonmatching D_8009AF5C

dlabel D_8009AF5C
    /* 8B75C 8009AF5C FFFF9000 */ .word 0x0090FFFF
    /* 8B760 8009AF60 A0000000 */ .word 0x000000A0
enddlabel D_8009AF5C

nonmatching D_8009AF64

dlabel D_8009AF64
    /* 8B764 8009AF64 55555555 */ .word 0x55555555
enddlabel D_8009AF64

nonmatching D_8009AF68

dlabel D_8009AF68
    /* 8B768 8009AF68 55555555 */ .word 0x55555555
enddlabel D_8009AF68

.align 2
nonmatching D_8009AF6C

dlabel D_8009AF6C
    /* 8B76C 8009AF6C */ .asciz "%s\n"
    /* 25730A00 */
.align 2
enddlabel D_8009AF6C

.align 2
nonmatching D_8009AF70

dlabel D_8009AF70
    /* 8B770 8009AF70 */ .asciz "*"
    /* 2A000000 */
.align 2
enddlabel D_8009AF70

nonmatching D_8009AF74

dlabel D_8009AF74
    /* 8B774 8009AF74 */ .short 0x0000
enddlabel D_8009AF74

nonmatching D_8009AF76

dlabel D_8009AF76
    /* 8B776 8009AF76 */ .byte 0x20
    /* 8B777 8009AF77 */ .byte 0x00
    /* 8B778 8009AF78 */ .short 0x0800
enddlabel D_8009AF76

nonmatching D_8009AF7A

dlabel D_8009AF7A
    /* 8B77A 8009AF7A */ .short 0x0020
enddlabel D_8009AF7A

.align 2
nonmatching D_8009AF7C

dlabel D_8009AF7C
    /* 8B77C 8009AF7C */ .asciz "*"
    /* 2A000000 */
.align 2
enddlabel D_8009AF7C

.align 2
nonmatching D_8009AF80

dlabel D_8009AF80
    /* 8B780 8009AF80 */ .asciz "MTrk"
    /* 4D54726B00000000 */
.align 2
enddlabel D_8009AF80

nonmatching D_8009AF88

dlabel D_8009AF88
    /* 8B788 8009AF88 08100980 */ .word D_80091008
enddlabel D_8009AF88

nonmatching D_8009AF8C

dlabel D_8009AF8C
    /* 8B78C 8009AF8C */ .short 0x012C
enddlabel D_8009AF8C

nonmatching D_8009AF8E

dlabel D_8009AF8E
    /* 8B78E 8009AF8E */ .short 0x0000
enddlabel D_8009AF8E

nonmatching D_8009AF90

dlabel D_8009AF90
    /* 8B790 8009AF90 */ .short 0x0000
enddlabel D_8009AF90

nonmatching D_8009AF92

dlabel D_8009AF92
    /* 8B792 8009AF92 */ .short 0x0000
enddlabel D_8009AF92

nonmatching D_8009AF94

dlabel D_8009AF94
    /* 8B794 8009AF94 */ .byte 0x00
    /* 8B795 8009AF95 */ .byte 0x00
enddlabel D_8009AF94

nonmatching D_8009AF96

dlabel D_8009AF96
    /* 8B796 8009AF96 */ .short 0x0000
enddlabel D_8009AF96

nonmatching D_8009AF98

dlabel D_8009AF98
    /* 8B798 8009AF98 */ .byte 0x00
enddlabel D_8009AF98

nonmatching D_8009AF99

dlabel D_8009AF99
    /* 8B799 8009AF99 */ .byte 0x01
enddlabel D_8009AF99

nonmatching D_8009AF9A

dlabel D_8009AF9A
    /* 8B79A 8009AF9A */ .byte 0xFF
enddlabel D_8009AF9A

nonmatching D_8009AF9B

dlabel D_8009AF9B
    /* 8B79B 8009AF9B */ .byte 0x00
enddlabel D_8009AF9B

nonmatching D_8009AF9C

dlabel D_8009AF9C
    /* 8B79C 8009AF9C 00000000 */ .word 0x00000000
enddlabel D_8009AF9C

nonmatching D_8009AFA0

dlabel D_8009AFA0
    /* 8B7A0 8009AFA0 */ .byte 0x00
enddlabel D_8009AFA0

nonmatching D_8009AFA1

dlabel D_8009AFA1
    /* 8B7A1 8009AFA1 */ .byte 0x00
enddlabel D_8009AFA1

nonmatching D_8009AFA2

dlabel D_8009AFA2
    /* 8B7A2 8009AFA2 */ .byte 0x00
enddlabel D_8009AFA2

nonmatching D_8009AFA3

dlabel D_8009AFA3
    /* 8B7A3 8009AFA3 */ .byte 0x00
enddlabel D_8009AFA3

nonmatching D_8009AFA4

dlabel D_8009AFA4
    /* 8B7A4 8009AFA4 */ .byte 0x01
    /* 8B7A5 8009AFA5 */ .byte 0x00
enddlabel D_8009AFA4

nonmatching D_8009AFA6

dlabel D_8009AFA6
    /* 8B7A6 8009AFA6 */ .byte 0x00
    /* 8B7A7 8009AFA7 */ .byte 0x00
    /* 8B7A8 8009AFA8 */ .byte 0x01
    /* 8B7A9 8009AFA9 */ .byte 0x00
    /* 8B7AA 8009AFAA */ .byte 0x00
    /* 8B7AB 8009AFAB */ .byte 0x00
enddlabel D_8009AFA6

nonmatching D_8009AFAC

dlabel D_8009AFAC
    /* 8B7AC 8009AFAC 80808024 */ .word 0x24808080
enddlabel D_8009AFAC

nonmatching D_8009AFB0

dlabel D_8009AFB0
    /* 8B7B0 8009AFB0 8080802C */ .word 0x2C808080
enddlabel D_8009AFB0

nonmatching D_8009AFB4

dlabel D_8009AFB4
    /* 8B7B4 8009AFB4 80808034 */ .word 0x34808080
enddlabel D_8009AFB4

nonmatching D_8009AFB8

dlabel D_8009AFB8
    /* 8B7B8 8009AFB8 8080803C */ .word 0x3C808080
enddlabel D_8009AFB8

nonmatching D_8009AFBC

dlabel D_8009AFBC
    /* 8B7BC 8009AFBC 40404024 */ .word 0x24404040
enddlabel D_8009AFBC

nonmatching D_8009AFC0

dlabel D_8009AFC0
    /* 8B7C0 8009AFC0 4040402C */ .word 0x2C404040
enddlabel D_8009AFC0

nonmatching D_8009AFC4

dlabel D_8009AFC4
    /* 8B7C4 8009AFC4 40404034 */ .word 0x34404040
enddlabel D_8009AFC4

nonmatching D_8009AFC8

dlabel D_8009AFC8
    /* 8B7C8 8009AFC8 4040403C */ .word 0x3C404040
enddlabel D_8009AFC8

nonmatching D_8009AFCC

dlabel D_8009AFCC
    /* 8B7CC 8009AFCC 8080804A */ .word 0x4A808080
enddlabel D_8009AFCC

nonmatching D_8009AFD0

dlabel D_8009AFD0
    /* 8B7D0 8009AFD0 8080804E */ .word 0x4E808080
enddlabel D_8009AFD0

nonmatching D_8009AFD4

dlabel D_8009AFD4
    /* 8B7D4 8009AFD4 200200E1 */ .word 0xE1000220
enddlabel D_8009AFD4

nonmatching D_8009AFD8

dlabel D_8009AFD8
    /* 8B7D8 8009AFD8 00000000 */ .word 0x00000000
enddlabel D_8009AFD8

nonmatching D_8009AFDC

dlabel D_8009AFDC
    /* 8B7DC 8009AFDC 00000000 */ .word 0x00000000
enddlabel D_8009AFDC

nonmatching D_8009AFE0

dlabel D_8009AFE0
    /* 8B7E0 8009AFE0 00000000 */ .word 0x00000000
enddlabel D_8009AFE0

nonmatching D_8009AFE4

dlabel D_8009AFE4
    /* 8B7E4 8009AFE4 */ .byte 0x00
enddlabel D_8009AFE4

nonmatching D_8009AFE5

dlabel D_8009AFE5
    /* 8B7E5 8009AFE5 */ .byte 0x00
enddlabel D_8009AFE5

nonmatching D_8009AFE6

dlabel D_8009AFE6
    /* 8B7E6 8009AFE6 */ .byte 0x00
    /* 8B7E7 8009AFE7 */ .byte 0x00
enddlabel D_8009AFE6

nonmatching D_8009AFE8

dlabel D_8009AFE8
    /* 8B7E8 8009AFE8 */ .byte 0x00
enddlabel D_8009AFE8

nonmatching D_8009AFE9

dlabel D_8009AFE9
    /* 8B7E9 8009AFE9 */ .byte 0x00
    /* 8B7EA 8009AFEA */ .short 0x0000
enddlabel D_8009AFE9

nonmatching D_8009AFEC

dlabel D_8009AFEC
    /* 8B7EC 8009AFEC 00000010 */ .word 0x10000000
    /* 8B7F0 8009AFF0 00000400 */ .word 0x00040000
enddlabel D_8009AFEC

.align 2
nonmatching D_8009AFF4

dlabel D_8009AFF4
    /* 8B7F4 8009AFF4 */ .asciz "WHY?\n"
    /* 5748593F0A000000 */
.align 2
enddlabel D_8009AFF4

nonmatching D_8009AFFC

dlabel D_8009AFFC
    /* 8B7FC 8009AFFC 000024FA */ .word 0xFA240000
    /* 8B800 8009B000 00000000 */ .word 0x00000000
enddlabel D_8009AFFC

nonmatching D_8009B004

dlabel D_8009B004
    /* 8B804 8009B004 00000000 */ .word 0x00000000
enddlabel D_8009B004

nonmatching D_8009B008

dlabel D_8009B008
    /* 8B808 8009B008 00000000 */ .word 0x00000000
enddlabel D_8009B008

.align 2
nonmatching D_8009B00C

dlabel D_8009B00C
    /* 8B80C 8009B00C */ .asciz "~cff0"
    /* 7E63666630000000 */
.align 2
enddlabel D_8009B00C

.align 2
nonmatching D_8009B014

dlabel D_8009B014
    /* 8B814 8009B014 */ .asciz "~cf00"
    /* 7E63663030000000 */
.align 2
enddlabel D_8009B014

.align 2
nonmatching D_8009B01C

dlabel D_8009B01C
    /* 8B81C 8009B01C */ .asciz "%s%d"
    /* 2573256400000000 */
.align 2
enddlabel D_8009B01C

.align 2
nonmatching D_8009B024

dlabel D_8009B024
    /* 8B824 8009B024 */ .asciz " VS "
    /* 2056532000000000 */
.align 2
enddlabel D_8009B024

.align 2
nonmatching D_8009B02C

dlabel D_8009B02C
    /* 8B82C 8009B02C */ .asciz "\n"
    /* 0A000000 */
.align 2
enddlabel D_8009B02C

.align 2
nonmatching D_8009B030

dlabel D_8009B030
    /* 8B830 8009B030 */ .asciz "BACK\n"
    /* 4241434B0A000000 */
.align 2
enddlabel D_8009B030

.align 2
nonmatching D_8009B038

dlabel D_8009B038
    /* 8B838 8009B038 */ .asciz "STONE\n"
    /* 53544F4E450A0000 */
.align 2
enddlabel D_8009B038

.align 2
nonmatching D_8009B040

dlabel D_8009B040
    /* 8B840 8009B040 */ .asciz "HIT\n"
    /* 4849540A00000000 */
.align 2
enddlabel D_8009B040

.align 2
nonmatching D_8009B048

dlabel D_8009B048
    /* 8B848 8009B048 */ .asciz "OUCH\n"
    /* 4F5543480A000000 */
.align 2
enddlabel D_8009B048

.align 2
nonmatching D_8009B050

dlabel D_8009B050
    /* 8B850 8009B050 */ .asciz "TERM\n"
    /* 5445524D0A000000 */
.align 2
enddlabel D_8009B050

nonmatching D_8009B058

dlabel D_8009B058
    /* 8B858 8009B058 0000F000 */ .word 0x00F00000
    /* 8B85C 8009B05C 00010800 */ .word 0x00080100
enddlabel D_8009B058

nonmatching D_8009B060

dlabel D_8009B060
    /* 8B860 8009B060 */ .byte 0x00
enddlabel D_8009B060

nonmatching D_8009B061

dlabel D_8009B061
    /* 8B861 8009B061 */ .byte 0x00
enddlabel D_8009B061

nonmatching D_8009B062

dlabel D_8009B062
    /* 8B862 8009B062 */ .byte 0x00
enddlabel D_8009B062

nonmatching D_8009B063

dlabel D_8009B063
    /* 8B863 8009B063 */ .byte 0x00
enddlabel D_8009B063

nonmatching D_8009B064

dlabel D_8009B064
    /* 8B864 8009B064 */ .byte 0x00
enddlabel D_8009B064

nonmatching D_8009B065

dlabel D_8009B065
    /* 8B865 8009B065 */ .byte 0x00
enddlabel D_8009B065

nonmatching D_8009B066

dlabel D_8009B066
    /* 8B866 8009B066 */ .byte 0x00
enddlabel D_8009B066

nonmatching D_8009B067

dlabel D_8009B067
    /* 8B867 8009B067 */ .byte 0x00
enddlabel D_8009B067

nonmatching D_8009B068

dlabel D_8009B068
    /* 8B868 8009B068 00000000 */ .word 0x00000000
enddlabel D_8009B068

nonmatching D_8009B06C

dlabel D_8009B06C
    /* 8B86C 8009B06C 00000000 */ .word 0x00000000
enddlabel D_8009B06C

nonmatching D_8009B070

dlabel D_8009B070
    /* 8B870 8009B070 00000000 */ .word 0x00000000
enddlabel D_8009B070

nonmatching D_8009B074

dlabel D_8009B074
    /* 8B874 8009B074 00000000 */ .word 0x00000000
enddlabel D_8009B074

nonmatching D_8009B078

dlabel D_8009B078
    /* 8B878 8009B078 */ .byte 0x00
enddlabel D_8009B078

nonmatching D_8009B079

dlabel D_8009B079
    /* 8B879 8009B079 */ .byte 0x00
enddlabel D_8009B079

nonmatching D_8009B07A

dlabel D_8009B07A
    /* 8B87A 8009B07A */ .byte 0xFF
enddlabel D_8009B07A

nonmatching D_8009B07B

dlabel D_8009B07B
    /* 8B87B 8009B07B */ .byte 0x00
enddlabel D_8009B07B

nonmatching D_8009B07C

dlabel D_8009B07C
    /* 8B87C 8009B07C */ .byte 0x00
    /* 8B87D 8009B07D */ .byte 0x00
    /* 8B87E 8009B07E */ .byte 0x00
    /* 8B87F 8009B07F */ .byte 0x00
    /* 8B880 8009B080 */ .byte 0x00
    /* 8B881 8009B081 */ .byte 0x00
    /* 8B882 8009B082 */ .byte 0x00
    /* 8B883 8009B083 */ .byte 0x00
enddlabel D_8009B07C

.align 2
nonmatching D_8009B084

dlabel D_8009B084
    /* 8B884 8009B084 */ .asciz "%s:%d\n"
    /* 25733A25640A0000 */
.align 2
.align 2
    /* 8B88C 8009B08C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_8009B084
