#!/usr/bin/env python3
"""
Set up decomp-permuter for one function.

The permuter randomly rewrites a candidate C function -- reordering
declarations, introducing temporaries, changing types -- recompiles each
variant and scores it against the target object. It exists for exactly the
failure we keep hitting: the logic and instruction count are right but gcc
allocates registers differently, and no amount of hand-guessing at the C
finds the shape that reproduces the original.

    python tools_src/permute.py func_80035598
    python tools_src/permute.py func_80035598 --run

Without --run it only prepares build/permuter/<func>/ and prints the
command, so you can inspect or tweak before starting a long search.

Requires the candidate C to already exist at src/<func>.c -- the permuter
improves a near miss, it does not decompile from nothing.
"""

import argparse
import io
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools_src"))

import build as B  # noqa: E402  (shares toolchain paths and flag tables)

PERMUTER = ROOT / "tools" / "decomp-permuter"
OUTDIR = ROOT / "build" / "permuter"


def patch_permuter_for_windows():
    """Skip the permuter's executable-bit check, which Windows cannot pass.

    permuter.py refuses to start unless compile.sh has mode bit 0o100.
    On Windows os.chmod cannot set it -- os.stat reports 0o100666 for any
    writable file regardless -- so the check fails for everyone on this
    platform. Relaxing it to "only enforce off Windows" is the smallest
    change that works; it is idempotent, so re-running is harmless.

    This patches a cloned third-party tool, which is worth doing
    deliberately rather than by accident: re-cloning decomp-permuter
    reverts it, and running this script again re-applies it.
    """
    patches = [
        # 1. The executable-bit check itself.
        (PERMUTER / "src" / "main.py",
         "        if not os.stat(compile_cmd).st_mode & 0o100:",
         "        if os.name != \"nt\" and "
         "not os.stat(compile_cmd).st_mode & 0o100:"),
        # 2. Windows cannot exec a .sh directly, so route it through bash.
        (PERMUTER / "src" / "compiler.py",
         "                [self.compile_cmd, c_name, \"-o\", o_name],",
         "                ([\"bash\"] if os.name == \"nt\" else [])\n"
         "                + [self.compile_cmd, c_name, \"-o\", o_name],"),
    ]
    changed = False
    for path, old, new in patches:
        text = path.read_text(encoding="utf-8")
        if new in text:
            continue
        if old not in text:
            print(f"warning: could not patch {path.name}; decomp-permuter "
                  f"may have changed", file=sys.stderr)
            continue
        text = text.replace(old, new)
        if path.name == "compiler.py" and "\nimport os" not in text:
            text = text.replace("import subprocess", "import os\nimport subprocess", 1)
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        changed = True
    return changed


def make_tool_shims():
    """Expose the toolchain under the names the permuter looks for.

    It locates objdump with shutil.which() against a fixed list of names
    (mips-linux-gnu-objdump and friends) and shells out to a bare `cpp`.
    Ours are prefixed mipsel-none-elf-*, so we drop copies under the
    expected names rather than patching the tool further.

    The copies go *inside* the toolchain's own bin directory, not a
    separate shim directory: `cpp` is a driver that locates its `cc1`
    relative to its own location, so a copy anywhere else fails with
    "cannot execute 'cc1'". tools/ is gitignored, so this leaves no trace
    in the repo.
    """
    bindir = B.MIPS_BIN
    for want, have in (("mips-linux-gnu-objdump.exe", "mipsel-none-elf-objdump.exe"),
                       ("cpp.exe", "mipsel-none-elf-cpp.exe")):
        shim, real = bindir / want, bindir / have
        if not shim.exists() or shim.stat().st_mtime < real.stat().st_mtime:
            shutil.copy2(real, shim)
    return bindir


def write_compile_script(dest: Path, flags, as_flags):
    """The permuter invokes this as `./compile.sh input.c -o output.o`.

    Its input is already preprocessed, so this skips cpppsx and runs the
    same cc1psx -> maspsx -> as chain the real build uses. Keeping it in
    step with build.py matters: a variant that matches here but is
    compiled differently by the build is worthless.
    """
    script = f"""#!/bin/bash
# Generated by tools_src/permute.py -- mirrors the build's compile pipeline.
set -e
INPUT="$1"; shift
OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o) OUT="$2"; shift 2 ;;
    *) shift ;;
  esac
done
# Resolve before changing directory: the permuter passes these relative to
# its own working directory, but the assembler needs to run from the repo
# root so that .include paths resolve.
INPUT="$(realpath "$INPUT")"
OUT="$(realpath -m "$OUT")"
cd "{ROOT.as_posix()}"
ASM="$(mktemp).s"
MASM="$(mktemp).maspsx.s"
"{B.CC1PSX.as_posix()}" {' '.join(flags)} "$INPUT" -o "$ASM"
"{B.VENV_PYTHON.as_posix()}" "{B.MASPSX.as_posix()}" \\
    --aspsx-version={B.ASPSX_VERSION} --macro-inc < "$ASM" > "$MASM"
"{B.AS.as_posix()}" {' '.join(as_flags)} -o "$OUT" "$MASM"
rm -f "$ASM" "$MASM"
"""
    with io.open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write(script)
    dest.chmod(0o755)


def build_target_object(func: str, dest: Path, as_flags):
    """Assemble the original disassembly into the object to match against."""
    stub = dest.parent / "target.s"
    with io.open(stub, "w", encoding="utf-8", newline="\n") as f:
        f.write('.include "include/macro.inc"\n\n.section .text\n'
                '.set noat\n.set noreorder\n\n'
                f'.include "asm/nonmatchings/31D8/{func}.s"\n')
    subprocess.run(
        [str(B.AS), *as_flags, "-o", str(dest), str(stub)],
        cwd=ROOT, check=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("func", help="function name, e.g. func_80035598")
    ap.add_argument("--run", action="store_true",
                    help="start the permuter instead of only preparing")
    ap.add_argument("-j", default="4", help="permuter worker threads")
    args = ap.parse_args()

    src = ROOT / "src" / f"{args.func}.c"
    if not src.exists():
        sys.exit(f"{src} does not exist -- write a candidate first; the "
                 f"permuter refines a near miss, it cannot start from nothing")
    if not (B.ASM_FUNCS / f"{args.func}.s").exists():
        sys.exit(f"no disassembly for {args.func}")

    flags = [f for f in B.PER_FUNC_FLAGS.get(args.func, B.CC1_FLAGS)]
    as_flags = list(B.AS_FLAGS)
    override = B.PER_FUNC_AS_FLAGS.get(args.func)
    if override:
        as_flags.append(override)

    if patch_permuter_for_windows():
        print("patched decomp-permuter: relaxed its executable-bit check on Windows")

    work = OUTDIR / args.func
    work.mkdir(parents=True, exist_ok=True)

    # base.c: preprocessed, reduced to just this function.
    base = work / "base.c"
    B.run([B.CPPPSX, *B.CPP_FLAGS, src.relative_to(ROOT).as_posix(),
           base.relative_to(ROOT).as_posix()])
    subprocess.run([str(B.VENV_PYTHON), str(PERMUTER / "strip_other_fns.py"),
                    str(base), args.func], cwd=ROOT, check=True)

    bindir = make_tool_shims()

    write_compile_script(work / "compile.sh", flags, as_flags)
    build_target_object(args.func, work / "target.o", as_flags)

    cmd = (f'"{B.VENV_PYTHON.as_posix()}" '
           f'"{(PERMUTER / "permuter.py").as_posix()}" '
           f'"{work.as_posix()}" -j {args.j} --better-only --stop-on-zero')
    print(f"\nprepared {work.relative_to(ROOT)}")
    print(f"compiler flags: {' '.join(flags)}")
    print(f"\n{cmd}\n")

    if args.run:
        # Windows resolves a child's program name against the *parent's*
        # PATH, so setting it on the child env alone would not work.
        os.environ["PATH"] = f"{bindir}{os.pathsep}{os.environ['PATH']}"
        subprocess.run(cmd, shell=True, cwd=ROOT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
